import subprocess,pathlib,json,hashlib,datetime,platform
root=pathlib.Path(__file__).resolve().parents[3];out=root/'docs/evidence/fr-evolution'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
inputs={str(p.relative_to(root)):sha(p) for p in (list((root/'starter-kit/scripts').rglob('*'))+list((root/'starter-kit/templates').glob('*'))+list((root/'starter-kit/tests').glob('*.py'))) if p.is_file()}
evidence=[]
for ident,cmd,paths in [('kit-tests',['python3','starter-kit/tests/test_gates.py'],inputs),('decision-tests',['python3','scripts/test_decisions.py'],{n:sha(root/n) for n in ['scripts/check-decisions.py','scripts/test_decisions.py']}),('plan-structure',['sh','starter-kit/scripts/check-readiness.sh','docs/planning/fr-evolution.md'],{n:sha(root/n) for n in ['starter-kit/scripts/check-readiness.sh','docs/planning/fr-evolution.md']})]:
 p=subprocess.run(cmd,cwd=root,capture_output=True,text=True,timeout=60);r={'command':cmd,'exit_code':p.returncode,'stdout':p.stdout,'stderr':p.stderr,'source_base':subprocess.check_output(['git','rev-parse','HEAD'],cwd=root,text=True).strip(),'observed_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'host':platform.platform(),'worker':'Codex','python':platform.python_version(),'inputs':paths,'scope':'Actual local development checks; fixtures synthetic; no comparative research performance claim.'}
 f=out/(ident+'.json');f.write_text(json.dumps(r,indent=2)+'\n')
 if p.returncode:raise SystemExit(r)
 evidence.append({'id':ident,'kind':'execution','artifact':str(f.relative_to(root)),'sha256':sha(f),'inputs':paths,'scope':r['scope'],'visibility':'public'})
claims=[{'id':'kit-repairs','text':'Installed synthetic regression cases for missing registries, staged proofs and shared ledger checks pass.','status':'supported','evidence':['kit-tests'],'depends_on':[]},{'id':'portable-records','text':'Development fixtures cover identity changes, dependency propagation and controlled export.','status':'supported','evidence':['decision-tests'],'depends_on':[]},{'id':'net-benefit','text':'Whether decision records reduce real operator work at unchanged research quality is unmeasured.','status':'provisional','evidence':['decision-tests'],'depends_on':['portable-records']}]
decisions=[{'id':'gate-repair','question':'Adopt the bounded starter-kit corrections?','owner':'maintainer','priority':0,'next_check':'Review implementation and full site gate receipt before merge.','alternatives':['retain current kit','adopt corrected kit'],'disposition':'combine','claims':['kit-repairs']},{'id':'decision-workflow','question':'Invest in the portable decision workflow or a separate wr product?','owner':'maintainer','priority':1,'next_check':'Run fresh paired review/handoff tasks with approved effort cap; no speedup is established.','alternatives':['FR documents alone','FR with optional decision records','separate wr'],'disposition':'defer','claims':['portable-records','net-benefit']}]
(out/'decisions.json').write_text(json.dumps({'version':1,'evidence':evidence,'claims':claims,'decisions':decisions},indent=2)+'\n')
print('Captured actual checks; comparative benefit left provisional.')
