#!/usr/bin/env bash
# verify-site.sh — pre-ship gates for the Franken Research site.
#
# Run from anywhere:  ./scripts/verify-site.sh   (from site/)
#                     bash site/scripts/verify-site.sh
# Prints PASS/FAIL per gate and exits 0 only if every gate passes.
# What each gate checks and why is documented in ../BUILD-GATES.md.
set -u

SITE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Canonical packets + Rulebook live at the repo root (one level above site/).
# Override with CANON=/path for a detached tree.
CANON="${CANON:-$(cd "$SITE_DIR/.." && pwd)}"
# Hand-written pages every structural gate scans (briefs are globbed on top).
# A listed page that does not exist fails the gates that open it.
# stack/index.html, rigor/index.html and every stack/<slug>.html are generated by
# scripts/make-stack.mjs (Gate K4 proves they match their sources); beyond/ is hand-written.
SITE_PAGES="index.html method/index.html failure-modes/index.html lessons/index.html
techniques/index.html reproduce/index.html starter-kit/index.html self/index.html
stack/index.html rigor/index.html beyond/index.html updates/index.html"
for _p in "$SITE_DIR"/stack/*.html; do
  case "$_p" in */stack/index.html|*'/stack/*.html') ;; *) SITE_PAGES="$SITE_PAGES stack/${_p##*/}" ;; esac
done
# The repository root: stack/, ecosystem/ and starter-kit/ live here (Gate K).
REPO_ROOT="$(cd "$SITE_DIR/.." && pwd)"
export SITE_DIR CANON SITE_PAGES REPO_ROOT

PASS=0
FAIL=0
FAILED_GATES=()

pass() { PASS=$((PASS+1)); echo "PASS  $1"; }
fail() {
  FAIL=$((FAIL+1)); echo "FAIL  $1"; FAILED_GATES+=("$1")
  if [ -n "${2:-}" ]; then echo "      $2"; fi
}

# Extract "<LABEL> <N>" from a gate's output (portable; BSD grep has no -P).
count_of() { printf '%s\n' "$1" | sed -n "s/^$2 \([0-9][0-9]*\).*/\1/p" | head -1; }

echo "Franken Research site gates — $SITE_DIR"
echo "----------------------------------------"

# ============ Gate A: packet + Rulebook byte integrity, method citations ============
echo "== A  packet/rulebook byte integrity =="
A_OK=1
A_DETAIL=""
# Repo layout keeps canonical packets in packets/; a flat canon dir holds them at its top.
CANON_PACKETS="$CANON"; [ -d "$CANON/packets" ] && CANON_PACKETS="$CANON/packets"
for f in "$CANON_PACKETS"/*-assessment.md; do
  base="$(basename "$f")"
  if [ ! -f "$SITE_DIR/packets/$base" ]; then
    A_OK=0; A_DETAIL="${A_DETAIL}missing:$base "
  elif ! cmp -s "$f" "$SITE_DIR/packets/$base"; then
    A_OK=0; A_DETAIL="${A_DETAIL}differs:$base "
  fi
done
for f in "$SITE_DIR"/packets/*.md; do
  base="$(basename "$f")"
  if [ ! -f "$CANON_PACKETS/$base" ]; then
    A_OK=0; A_DETAIL="${A_DETAIL}extra:$base "
  fi
done
if ! cmp -s "$CANON/RULEBOOK.md" "$SITE_DIR/RULEBOOK.md"; then
  A_OK=0; A_DETAIL="${A_DETAIL}RULEBOOK-differs "
fi
if [ $A_OK -eq 1 ]; then
  pass "A packet/rulebook byte-identical ($(ls "$SITE_DIR"/packets/*.md | wc -l | tr -d ' ') packets + RULEBOOK)"
else
  fail "A packet/rulebook byte-identical" "$A_DETAIL"
fi

echo "== A2 method-page claim citations =="
A2_OUT="$(python3 - <<'PYEOF'
import re, html as h, os, sys
site = os.environ['SITE_DIR']
def norm(s):
    s = h.unescape(s)
    s = re.sub(r'`([^`]*)`', r'\1', s)
    s = re.sub(r'\*\*([^*]*)\*\*', r'\1', s)
    s = re.sub(r'\[([^\]]*)\]\([^)]*\)', r'\1', s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s
errs = []
try:
    t = open(site + '/method/index.html').read()
    texts = re.findall(r'<div class="cr-text">(.*?)</div>', t, re.S)
    srcs = re.findall(r'<span class="cr-src">(.*?)</span>', t)
    if not texts:
        errs.append('no .cr-text citations found')
    if len(texts) != len(srcs):
        errs.append('mismatched cr-text (%d) vs cr-src (%d)' % (len(texts), len(srcs)))
    for q, s in zip(texts, srcs):
        m = re.match(r'^([\w.\-]+\.md):(\d+)$', s.strip())
        if not m:
            errs.append('bad citation format: %r' % s); continue
        fn, ln = m.group(1), int(m.group(2))
        pp = site + '/packets/' + fn
        if not os.path.isfile(pp):
            errs.append('cited packet missing: %s' % fn); continue
        lines = open(pp).read().split('\n')
        if not (1 <= ln <= len(lines)):
            errs.append('%s:%d line out of range' % (fn, ln)); continue
        line = lines[ln - 1]
        if not re.match(r'^\|\s*\d+\s*\|', line):
            errs.append('%s:%d is not a claim-table row' % (fn, ln)); continue
        qq = norm(q).strip('"“”')
        if norm(qq) not in norm(line):
            errs.append('quote not in cited line %s:%d: %r' % (fn, ln, qq[:60]))
except Exception as e:
    errs.append('checker error: %s' % e)
print('CITATIONS_OK %d' % len(texts) if not errs else 'CITATIONS_BAD')
for e in errs:
    print('  ' + e)
PYEOF
)"
if echo "$A2_OUT" | head -1 | grep -q CITATIONS_OK; then
  pass "A2 method citations resolve ($(echo "$A2_OUT" | head -1 | grep -o '[0-9]*') claim rows)"
else
  fail "A2 method citations resolve" "$(echo "$A2_OUT" | tail -n +2 | head -4 | tr '\n' ';')"
fi

# ============ Gate B: statistics computed at render time ============
echo "== B  render-time statistics =="
B_OUT="$(python3 - <<'PYEOF'
import re, html as h, os, glob, sys

site = os.environ['SITE_DIR']
errs = []
src = open(site + '/assets/data.js').read()

# --- parse data.js: window.FRANKEN_DATA = { "framing": "...", "repos": [ {...}, ... ] } ---
rows = []
for m in re.finditer(r'\{\n\s*"name":\s*"([^"]+)",(.*?)\n\s*\}', src, re.S):
    body = m.group(0)
    g = lambda k: re.search(r'"' + k + r'":\s*"([^"]*)"', body)
    gi = lambda k: re.search(r'"' + k + r'":\s*(\d+)', body)
    try:
        rows.append({
            'name': m.group(1),
            'nodus': g('nodus').group(1),
            'licenseKey': g('licenseKey').group(1),
            'ciKey': g('ciKey').group(1),
            'trlLow': int(gi('trlLow').group(1)) if gi('trlLow') else None,
            'trlHigh': int(gi('trlHigh').group(1)) if gi('trlHigh') else None,
            'techNA': '"techNA": true' in body,
        })
    except AttributeError:
        pass
if not rows:
    errs.append('could not parse REPOS from data.js')

rings = {'Invest': 0, 'Pilot': 0, 'Explore': 0, 'Monitor': 0}
ci = {}
green_names = []
lic = {'rider': 0, 'mit': 0, 'none': 0}
trl_lo, trl_hi = 9, 2
for r in rows:
    rings[r['nodus']] = rings.get(r['nodus'], 0) + 1
    ci[r['ciKey']] = ci.get(r['ciKey'], 0) + 1
    lic[r['licenseKey']] = lic.get(r['licenseKey'], 0) + 1
    if r['ciKey'] == 'C1':
        green_names.append(r['name'])
    if not r['techNA'] and r['trlLow'] is not None:
        trl_lo = min(trl_lo, r['trlLow'])
        trl_hi = max(trl_hi, r['trlHigh'])
green_names.sort()
STATS = {
    'total': len(rows), 'greenCount': len(green_names),
    'notGreen': len(rows) - len(green_names),
    'riderCount': lic['rider'], 'mitCount': lic['mit'], 'noneCount': lic['none'],
    'noRiderCount': lic['mit'] + lic['none'],
    'ringInvest': rings['Invest'], 'ringPilot': rings['Pilot'],
    'ringExplore': rings['Explore'], 'ringMonitor': rings['Monitor'],
    'trlRange': '%d\u2013%d' % (trl_lo, trl_hi),
    'greenNames': green_names,
    'ciC1': ci.get('C1', 0), 'ciC2': ci.get('C2', 0), 'ciC3': ci.get('C3', 0),
    'ciC4': ci.get('C4', 0), 'ciC5': ci.get('C5', 0), 'ciC6': ci.get('C6', 0),
}

def clean(s):
    s = re.sub(r'<[^>]+>', '', s)
    return re.sub(r'\s+', ' ', h.unescape(s)).strip()

pages = os.environ['SITE_PAGES'].split() + sorted(glob.glob(site + '/briefs/*.html'))

slot_n = 0
for p in pages:
    rel = p if p.startswith(site) else site + '/' + p
    t = open(rel).read()
    for m in re.finditer(r'<([a-z0-9]+)[^>]*data-stat="([A-Za-z0-9]+)"[^>]*>(.*?)</\1>', t, re.S | re.I):
        key, fallback = m.group(2), clean(m.group(3))
        slot_n += 1
        if key not in STATS:
            errs.append('%s: unknown data-stat key %r' % (os.path.basename(p), key)); continue
        exp = STATS[key]
        if key == 'greenNames':
            got = set(re.findall(r'[a-z][a-z0-9_]*', fallback.lower())) - {'and'}
            if got != set(exp):
                errs.append('%s: data-stat greenNames fallback %r != %r' % (os.path.basename(p), sorted(got), exp))
        elif fallback != str(exp):
            errs.append('%s: data-stat %s fallback %r != computed %r' % (os.path.basename(p), key, fallback, str(exp)))

# framesentence fallback must equal FRANKEN_DATA.framing after slot substitution
import json as _json
fm = re.search(r'"framing":\s*"((?:[^"\\]|\\.)*)"', src)
if fm and os.path.isfile(site + '/index.html'):
    framing = _json.loads('"' + fm.group(1) + '"')
    t = open(site + '/index.html').read()
    sm = re.search(r'<span id="framesentence">(.*?)</span>\s*The <span data-stat="ringPilot"', t, re.S)
    if sm:
        inner = sm.group(1)
        inner = re.sub(r'<[a-z0-9]+[^>]*data-stat="([A-Za-z0-9]+)"[^>]*>.*?</[a-z0-9]+>',
                        lambda m: str(STATS.get(m.group(1), '?')), inner, flags=re.S | re.I)
        if clean(inner) != re.sub(r'\s+', ' ', framing).strip():
            errs.append('index.html framesentence fallback != data.js framing')
    else:
        errs.append('index.html: #framesentence not found')

# hardcoded-stat literal scan (bare N/44 etc. outside slots and STAT-annotated synthesis counts)
HARD = [
    (r'\b\d+\s+of\s+44\b', 'N of 44'),
    (r'\b\d+/44\b', 'N/44'),
    (r'\b(three|thirty[\s-]?four|seven|zero)\b.{0,24}\b(pilots?|explorations?|monitors?)\b', 'ring word count'),
    (r'\b(0|3|34|7)\b.{0,12}\b(pilots?|explorations?|monitors?)\b', 'ring numeral count'),
    (r'\ball 44 briefs\b', 'all-44 nav label'),
]
for p in pages:
    rel = p if p.startswith(site) else site + '/' + p
    t = open(rel).read()
    t = re.sub(r'<(script|style)[^>]*>.*?</\1>', '', t, flags=re.S | re.I)
    # blank out data-stat slot contents and STAT-annotated regions (400 chars after annotation)
    t = re.sub(r'<[a-z0-9]+[^>]*data-stat="[A-Za-z0-9]+"[^>]*>.*?</[a-z0-9]+>', ' ', t, flags=re.S | re.I)
    # STAT-annotated synthesis counts: blank the annotation AND the ~400 chars after it (the literal)
    t = re.sub(r'<!--\s*STAT:.*?-->.{0,400}', ' ', t, flags=re.S)
    txt = re.sub(r'<[^>]+>', ' ', t)
    txt = re.sub(r'\s+', ' ', h.unescape(txt))
    for pat, label in HARD:
        for m in re.finditer(pat, txt, re.I):
            errs.append('%s: hardcoded stat (%s): %r' % (
                rel.replace(site + '/', ''), label, txt[max(0, m.start()-30):m.end()+30].strip()))
if slot_n == 0:
    errs.insert(0, 'empty scan set: zero data-stat slots found (a gate that checks nothing is not a pass)')
print('SLOTS %d' % slot_n)
print('STATS_OK' if not errs else 'STATS_BAD')
for e in errs[:12]:
    print('  ' + e)
if len(errs) > 12:
    print('  ... and %d more' % (len(errs) - 12))
PYEOF
)"
B_SLOTS="$(count_of "$B_OUT" SLOTS)"
if echo "$B_OUT" | grep -q '^STATS_OK' && [ "${B_SLOTS:-0}" -gt 0 ]; then
  pass "B stats computed at render time ($B_SLOTS data-stat slots checked)"
else
  fail "B stats computed at render time" "$(echo "$B_OUT" | tail -n +3 | head -4 | tr '\n' ';')"
fi

# ============ Gate C: key terms defined on first use ============
echo "== C  definitions on first use =="
C_OUT="$(python3 - <<'PYEOF'
import re, html as h, os, glob

site = os.environ['SITE_DIR']
errs = []

TERMS = {
    'NODUS':      re.compile(r'NODUS'),
    'TRL':        re.compile(r'\bTRL\b'),
    'CI':         re.compile(r'\bCI\b'),
    'rider':      re.compile(r'\brider\b', re.I),
    'pin':        re.compile(r'\bpin\b|\bpinned\b', re.I),
    'bus factor': re.compile(r'bus factor', re.I),
}
# definitional phrases that must appear in a pre-first-use vocab block
DEF_PHRASE = {
    'NODUS': re.compile(r'four-ring verdict'),
    'TRL': re.compile(r'technology readiness'),
    'CI': re.compile(r'continuous integration'),
    'rider': re.compile(r'withholding all rights|barring the AI labs|license clause withholding|bars OpenAI and Anthropic'),
    'pin': re.compile(r'exact commit|single commit'),
    'bus factor': re.compile(r'how many people'),
}
# inline glosses accepted at first use (front door pattern)
GLOSS = {
    'NODUS': re.compile(r'\([^)]*(?:four|4)[^)]*assessment rings?[^)]*\)'),
    'TRL': re.compile(r'technology-readiness\s*\(TRL\)|technology readiness level'),
    'CI': re.compile(r'CI\s*\(continuous integration\)'),
    'rider': re.compile(r'AI-lab license rider'),
    'pin': re.compile(r'pinned?\s*(?:[A-Z][a-z]+\s+\d{1,2},\s+\d{4}\s*|[A-Z][a-z]+\s+\d{4}\s*)?\((?:the )?(?:single |exact )?assessed commit\)'),
    'bus factor': re.compile(r'bus factor.{0,60}\(one maintainer'),
}

pages = os.environ['SITE_PAGES'].split() + sorted(glob.glob(site + '/briefs/*.html'))

for p in pages:
    rel = p if p.startswith(site) else site + '/' + p
    short = rel.replace(site + '/', '')
    t = open(rel).read()
    t = re.sub(r'<(script|style)[^>]*>.*?</\1>', '', t, flags=re.S | re.I)
    t = re.sub(r'<!--.*?-->', '', t, flags=re.S)
    vm = re.search(r'<div class="vocab"[^>]*>.*?</div>', t, re.S)
    def vis(x):
        x = re.sub(r'<[^>]+>', ' ', x)
        return re.sub(r'\s+', ' ', h.unescape(x)).strip()
    full_txt = vis(t)
    vocab_txt = vis(vm.group(0)) if vm else ''
    vstart = -1
    search_txt = full_txt
    if vocab_txt:
        i = full_txt.find(vocab_txt[:40])
        if i >= 0:
            vstart = i
            search_txt = full_txt[:i] + ' ' * len(vocab_txt) + full_txt[i + len(vocab_txt):]
    for name, rx in TERMS.items():
        m = rx.search(search_txt)
        if not m:
            continue
        ok = False
        # (1) vocab block before first use, containing the definitional phrase
        if vstart >= 0 and vstart < m.start() and DEF_PHRASE[name].search(vocab_txt):
            ok = True
        # (2) inline gloss within 120 chars on either side of first use
        if not ok and GLOSS[name].search(search_txt[max(0, m.start()-120):m.start() + 120]):
            ok = True
        if not ok:
            errs.append('%s: %r used before definition: %r' % (
                short, name, search_txt[max(0, m.start()-40):m.start()+60].strip()))

print('DEFS_OK' if not errs else 'DEFS_BAD')
for e in errs[:12]:
    print('  ' + e)
if len(errs) > 12:
    print('  ... and %d more' % (len(errs) - 12))
PYEOF
)"
if echo "$C_OUT" | grep -q '^DEFS_OK'; then
  pass "C key terms defined on first use"
else
  fail "C key terms defined on first use" "$(echo "$C_OUT" | tail -n +2 | head -4 | tr '\n' ';')"
fi

# ============ Gate D: brief <-> packet integrity ============
echo "== D  brief/packet pairing =="
D_OUT="$(python3 - <<'PYEOF'
import re, os, glob
site = os.environ['SITE_DIR']
errs = []
briefs = sorted(glob.glob(site + '/briefs/*.html'))
for b in briefs:
    name = os.path.basename(b)[:-5]
    t = open(b).read()
    pkt = '../packets/%s-assessment.md' % name
    n = t.count('href="%s"' % pkt)
    if n != 1:
        errs.append('%s: packet link %r appears %d times (want 1)' % (name, pkt, n))
    # brief must name its packet file in the footer sources area
    if ('%s-assessment.md' % name) not in t:
        errs.append('%s: packet filename not cited in brief body' % name)
packets = sorted(glob.glob(site + '/packets/*-assessment.md'))
pnames = set(os.path.basename(p)[:-len('-assessment.md')] for p in packets)
bnames = set(os.path.basename(b)[:-5] for b in briefs)
for p in sorted(pnames - bnames):
    errs.append('packet without brief: %s' % p)
for b in sorted(bnames - pnames):
    errs.append('brief without packet: %s' % b)
# data.js names must map 1:1 onto both
src = open(site + '/assets/data.js').read()
dnames = set(re.findall(r'\{\s*"name":\s*"([^"]+)"', src))
if dnames != bnames:
    errs.append('data.js names != brief names: %r' % sorted(dnames ^ bnames)[:6])
print('PAIR_OK' if not errs else 'PAIR_BAD')
for e in errs[:10]:
    print('  ' + e)
PYEOF
)"
if echo "$D_OUT" | grep -q '^PAIR_OK'; then
  pass "D brief/packet 1:1 pairing ($(ls "$SITE_DIR"/briefs/*.html | wc -l | tr -d ' ') briefs)"
else
  fail "D brief/packet 1:1 pairing" "$(echo "$D_OUT" | tail -n +2 | head -4 | tr '\n' ';')"
fi

# ============ Gate E: internal link graph ============
echo "== E  internal links =="
E_OUT="$(python3 - <<'PYEOF'
import re, os, glob
from urllib.parse import unquote
site = os.environ['SITE_DIR']
errs = []
pages = os.environ['SITE_PAGES'].split() + sorted(glob.glob(site + '/briefs/*.html'))
SKIP_PREFIX = ('http://', 'https://', '//', 'mailto:', 'tel:', 'data:', 'javascript:')
checked = 0
for p in pages:
    rel = p if p.startswith(site) else site + '/' + p
    short = rel.replace(site + '/', '')
    t = open(rel).read()
    t = re.sub(r'<(script|style)[^>]*>.*?</\1>', ' ', t, flags=re.S | re.I)
    ids = set(re.findall(r'id="([^"]+)"', t))
    for attr in ('href', 'src'):
        for m in re.finditer(attr + r'="([^"]*)"', t):
            raw = m.group(1).strip()
            if not raw or raw.startswith(SKIP_PREFIX) or raw.startswith('#'):
                if raw.startswith('#') and raw[1:] not in ids and raw != '#':
                    errs.append('%s: fragment %r has no matching id' % (short, raw))
                continue
            if raw == '#':
                continue  # JS-owned placeholder (verified in gate G)
            url = unquote(raw.split('#')[0])
            frag = raw.split('#')[1] if '#' in raw else None
            base = os.path.dirname(rel)
            target = os.path.normpath(os.path.join(base, url))
            if not target.startswith(site):
                errs.append('%s: link escapes site root: %r' % (short, raw)); continue
            if os.path.isdir(target):
                target = os.path.join(target, 'index.html')
            if not os.path.isfile(target):
                errs.append('%s: broken %s %r' % (short, attr, raw)); continue
            checked += 1
            if frag and target.endswith('.html'):
                tt = open(target).read()
                tt = re.sub(r'<(script|style)[^>]*>.*?</\1>', ' ', tt, flags=re.S | re.I)
                if ('id="%s"' % frag) not in tt:
                    errs.append('%s: fragment %r missing in %s' % (short, raw, target.replace(site + '/', '')))
if checked == 0:
    errs.insert(0, 'empty scan set: zero relative links resolved (a gate that checks nothing is not a pass)')
print('LINKS %d ok' % checked)
print('LINKS_OK' if not errs else 'LINKS_BAD')
for e in errs[:12]:
    print('  ' + e)
if len(errs) > 12:
    print('  ... and %d more' % (len(errs) - 12))
PYEOF
)"
E_LINKS="$(count_of "$E_OUT" LINKS)"
if echo "$E_OUT" | grep -q '^LINKS_OK' && [ "${E_LINKS:-0}" -gt 0 ]; then
  pass "E internal links resolve ($E_LINKS links)"
else
  fail "E internal links resolve" "$(echo "$E_OUT" | tail -n +3 | head -4 | tr '\n' ';')"
fi

# ============ Gate F: method-animation artifacts shipped ============
echo "== F  method artifacts =="
F_OK=1; F_DETAIL=""
# every cr-src citation target exists (covered in A2) + every station link on method page
F_OUT="$(python3 - <<'PYEOF'
import re, os
site = os.environ['SITE_DIR']
t = open(site + '/method/index.html').read()
hrefs = set(re.findall(r'href="(\.\./starter-kit/[^"]+)"', t))
errs = []
for h in sorted(hrefs):
    if not os.path.isfile(os.path.normpath(os.path.join(site + '/method', h))):
        errs.append('station link missing: %s' % h)
# every local asset referenced by any page must exist (css/js/img/svg/fonts)
import glob
for p in (os.environ['SITE_PAGES'].split() + sorted(glob.glob(site + '/briefs/*.html'))):
    rel = p if p.startswith(site) else site + '/' + p
    tt = open(rel).read()
    for m in re.finditer(r'(?:src|href)="((?:\.\./|\./)?assets/[^"]+|favicon\.svg|\.\./favicon\.svg)"', tt):
        a = os.path.normpath(os.path.join(os.path.dirname(rel), m.group(1)))
        if not os.path.isfile(a):
            errs.append('%s: asset missing: %s' % (os.path.basename(p), m.group(1)))
print('ART_OK' if not errs else 'ART_BAD')
for e in errs[:10]:
    print('  ' + e)
PYEOF
)"
if echo "$F_OUT" | grep -q '^ART_OK'; then
  pass "F method artifacts + local assets exist"
else
  fail "F method artifacts + local assets exist" "$(echo "$F_OUT" | tail -n +2 | head -4 | tr '\n' ';')"
fi

# ============ Gate G: keyboard operability + no-JS/no-WebGL/reduced-motion ============
echo "== G  keyboard + fallbacks =="
G_OUT="$(python3 - <<'PYEOF'
import re, os, glob
site = os.environ['SITE_DIR']
errs = []
# G1: every page has a skip link or the front door's equivalent landmark nav
for p in (os.environ['SITE_PAGES'].split() + sorted(glob.glob(site + '/briefs/*.html'))):
    rel = p if p.startswith(site) else site + '/' + p
    short = rel.replace(site + '/', '')
    t = open(rel).read()
    body = t.split('<body', 1)[1] if '<body' in t else t
    # interactive elements must be natively focusable or have tabindex/key handlers
    for m in re.finditer(r'<(div|span)[^>]*(?:onclick|role="button")[^>]*>', body):
        tag = m.group(0)
        if 'tabindex' not in tag and '<' not in tag:
            errs.append('%s: clickable %s without tabindex' % (short, m.group(1)))
    # details/summary disclosure widgets are keyboard-native; confirm no JS-only disclosure
    # G2: reduced-motion respected somewhere global
# G2: each page's CSS/JS must handle prefers-reduced-motion (or be a static page)
for p in (['index.html', 'method/index.html'] + sorted(glob.glob(site + '/briefs/*.html'))):
    rel = p if p.startswith(site) else site + '/' + p
    short = rel.replace(site + '/', '')
    t = open(rel).read()
    if 'prefers-reduced-motion' not in t:
        errs.append('%s: no prefers-reduced-motion handling' % short)
# G3: front door works without WebGL/JS: framesentence + stats fallbacks present, table view exists
t = open(site + '/index.html').read()
for needle in ['id="framesentence"', 'id="tableview"', 'id="stats"', '<noscript']:
    if needle not in t:
        errs.append('index.html: missing no-JS/no-WebGL fallback marker %s' % needle)
# G4: method page works without JS: claim rows are static HTML, animation is enhancement
t = open(site + '/method/index.html').read()
if t.count('class="claim-row') < 12:
    errs.append('method/index.html: claim rows not statically rendered (<12)')
if 'prefers-reduced-motion' not in t:
    errs.append('method/index.html: no prefers-reduced-motion handling')
print('A11Y_OK' if not errs else 'A11Y_BAD')
for e in errs[:10]:
    print('  ' + e)
PYEOF
)"
if echo "$G_OUT" | grep -q '^A11Y_OK'; then
  pass "G keyboard operability + fallbacks"
else
  fail "G keyboard operability + fallbacks" "$(echo "$G_OUT" | tail -n +2 | head -4 | tr '\n' ';')"
fi

# ============ Gate H: copy-quality slop scan ============
echo "== H  slop scan =="
H_OUT="$(python3 - <<'PYEOF'
import re, html as h, glob, os
site = os.environ['SITE_DIR']
fails, notes = [], []
pages = os.environ['SITE_PAGES'].split() + sorted(glob.glob(site + '/briefs/*.html'))
for p in pages:
    short = p.replace(site + '/', '')
    t = open(p if p.startswith(site) else site + '/' + p).read()
    t = re.sub(r'<(script|style)[^>]*>.*?</\1>', '', t, flags=re.S | re.I)
    t = re.sub(r'<!--.*?-->', '', t, flags=re.S)
    # em-dash: exclude UI/list separators (instance rows, list items, summaries)
    prose_lines = [ln for ln in t.split('\n')
                   if not re.search(r'<(li|summary)[^>]*>|class="repo"|class="count"', ln)]
    prose = h.unescape(re.sub(r'<[^>]+>', ' ', '\n'.join(prose_lines)))
    nd = prose.count('\u2014')
    if nd > 30:
        fails.append('%s: %d non-separator em-dashes (limit 30)' % (short, nd))
    txt = h.unescape(re.sub(r'<[^>]+>', ' ', t))
    for w in ['delve', 'tapestry']:
        for m in re.finditer(r'\b%s\b' % w, txt, re.I):
            fails.append('%s: filler %r: %r' % (short, w, txt[max(0,m.start()-40):m.end()+40].strip()))
    for w in ['unprecedented', 'revolutionary', 'game-changing']:
        for m in re.finditer(w, txt, re.I):
            fails.append('%s: unsupported superlative %r: %r' % (short, w, txt[max(0,m.start()-40):m.end()+40].strip()))
    for w in ['honestly', 'genuinely', 'landscape']:
        for m in re.finditer(r'\b%s\b' % w, txt, re.I):
            notes.append('%s: filler? %r: %r' % (short, w, txt[max(0,m.start()-40):m.end()+40].strip()))
    for w in ['best', 'most widely used', 'world-class', 'cutting-edge', 'state-of-the-art']:
        for m in re.finditer(w, txt, re.I):
            notes.append('%s: superlative? %r: %r' % (short, w, txt[max(0,m.start()-50):m.end()+50].strip()))
print('SLOP_OK' if not fails else 'SLOP_BAD')
for f in fails[:10]:
    print('  FAIL ' + f)
for n in notes[:8]:
    print('  note ' + n)
if len(notes) > 8:
    print('  note ... and %d more review notes' % (len(notes) - 8))
PYEOF
)"
if echo "$H_OUT" | grep -q '^SLOP_OK'; then
  pass "H slop scan"
  echo "$H_OUT" | grep '^  note' | head -8 | sed 's/^/      /'
else
  fail "H slop scan" "$(echo "$H_OUT" | grep '^  FAIL' | head -4 | tr '\n' ';')"
fi

# ============ Gate I: headless render (CDP) ============
# Loads pages via file:// (the site is designed to run straight from the ZIP
# with no server) in headless Chromium, checking for console errors and
# horizontal overflow at desktop and phone widths.
echo "== I  headless render =="
I_TMP="$(mktemp -d)"
cat > "$I_TMP/render.mjs" <<'MEOF'
import { spawn, execSync } from 'child_process';
import fs from 'fs';
import os from 'os';
import path from 'path';

const SITE = process.env.SITE_DIR;
// CHROME_PATH wins; otherwise the first installed Chromium-family browser.
// No browser found is a FAIL, never a skip: an unrun render gate is not a pass.
const CHROME = process.env.CHROME_PATH || [
  '/opt/meta-chromium/chrome',
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  '/Applications/Chromium.app/Contents/MacOS/Chromium',
  '/usr/bin/google-chrome', '/usr/bin/google-chrome-stable',
  '/usr/bin/chromium', '/usr/bin/chromium-browser',
].find((p) => fs.existsSync(p));
if (!CHROME) { console.log('RENDER_BAD'); console.log('  no Chromium found; set CHROME_PATH'); process.exit(1); }
// One generated verdict page (the first by name) stands in for all of them: they share one template.
const SLUG = (fs.existsSync(SITE + '/stack') ? fs.readdirSync(SITE + '/stack') : [])
  .filter((f) => f !== 'index.html' && f.endsWith('.html')).sort()[0];
if (!SLUG) { console.log('RENDER_BAD'); console.log('  no generated stack/<slug>.html to render'); process.exit(1); }
const PAGES = ['/index.html', '/method/index.html', '/briefs/asupersync.html', '/lessons/index.html', '/self/index.html',
  '/stack/index.html', '/stack/' + SLUG, '/rigor/index.html', '/beyond/index.html', '/updates/index.html'];
const VIEWPORTS = [[1440, 900], [390, 844]];

// file:// loading: the site is designed to run straight from the ZIP with no
// server, so the render gate tests exactly that. (An http://127.0.0.1 test
// server is unusable here: Chrome 152's local-network access checks block
// CDP-initiated navigation to loopback.)
// Chrome can take well over 15 s to start on a loaded CI runner. Wait up to 45 s for the
// DevTools port, and relaunch once (fresh profile) before failing. Harness robustness only:
// what the gate asserts about the pages is unchanged.
const DEVTOOLS_WAIT_MS = 45000;
let chrome = null, prof = null, dbgPort = null;
function launch() {
  prof = fs.mkdtempSync(path.join(os.tmpdir(), 'chrome-prof-'));
  chrome = spawn(CHROME, [
    // Software WebGL (SwiftShader) so the gate renders the real 3D path; current
    // Chrome refuses the software fallback unless it is enabled explicitly.
    '--headless=new', '--no-sandbox', '--use-angle=swiftshader', '--enable-unsafe-swiftshader',
    '--allow-file-access-from-files',
    '--remote-debugging-port=0', `--user-data-dir=${prof}`,
    '--no-first-run', '--disable-extensions', 'about:blank',
  ], { stdio: ['ignore', 'pipe', 'pipe'] });
  return new Promise((resolve, reject) => {
    const t = setTimeout(() => reject(new Error(`no devtools port after ${DEVTOOLS_WAIT_MS / 1000}s`)), DEVTOOLS_WAIT_MS);
    chrome.stderr.on('data', d => {
      const m = /DevTools listening on ws:\/\/127\.0\.0\.1:(\d+)/.exec(d.toString());
      if (m) { dbgPort = m[1]; clearTimeout(t); resolve(); }
    });
    chrome.on('exit', () => { clearTimeout(t); reject(new Error('chrome exited')); });
  });
}
for (let attempt = 1; ; attempt++) {
  try { await launch(); break; } catch (e) {
    if (chrome.exitCode === null && chrome.signalCode === null) {
      await new Promise((r) => { chrome.once('exit', r); chrome.kill('SIGKILL'); setTimeout(r, 5000); });
    }
    try { fs.rmSync(prof, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 }); } catch {}
    if (attempt >= 2) { console.log('RENDER_BAD'); console.log(`  chrome launch failed twice: ${e.message}`); process.exit(1); }
    console.error(`chrome launch attempt ${attempt} failed (${e.message}); retrying once`);
  }
}

const tabs = JSON.parse(execSync(`curl -s http://127.0.0.1:${dbgPort}/json/list`).toString());
// Desktop Chrome lists built-in extension background pages first; drive the tab.
const tab = tabs.find((t) => t.type === 'page');
if (!tab) { console.log('RENDER_BAD'); console.log('  no page target in ' + JSON.stringify(tabs.map((t) => t.type))); process.exit(1); }
const wsUrl = tab.webSocketDebuggerUrl;
const ws = new WebSocket(wsUrl);
await new Promise((r, rej) => { ws.onopen = r; ws.onerror = rej; });

let id = 0;
const pending = new Map();
let consoleEvents = [];
ws.onmessage = e => {
  const m = JSON.parse(e.data);
  if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); }
  else if (m.method === 'Runtime.consoleAPICalled') consoleEvents.push(m);
  else if (m.method === 'Runtime.exceptionThrown') consoleEvents.push(m);
  else if (m.method === 'Log.entryAdded') consoleEvents.push(m);
};
const send = (method, params = {}) => new Promise(res => {
  const myId = ++id;
  pending.set(myId, res);
  ws.send(JSON.stringify({ id: myId, method, params }));
});
const errors = [];
const sleep = ms => new Promise(r => setTimeout(r, ms));

await send('Runtime.enable');
await send('Log.enable');
await send('Page.enable');

for (const page of PAGES) {
  for (const vp of VIEWPORTS) {
    consoleEvents = [];
    await send('Emulation.setDeviceMetricsOverride', {
      width: vp[0], height: vp[1], deviceScaleFactor: 1, mobile: vp[0] < 500 });
    await send('Page.navigate', { url: `file://${SITE}${page}` });
    await sleep(3000); // let load + timers/animations settle
    const ev = await send('Runtime.evaluate', { returnByValue: true, expression: `(() => ({
      overflowX: document.documentElement.scrollWidth - document.documentElement.clientWidth,
      blank: document.body ? document.body.innerText.trim().length : 0,
      title: document.title
    }))()` });
    const v = ev.result.result.value;
    const label = `${page} @${vp[0]}x${vp[1]}`;
    if (!v || !v.title) { errors.push(`${label}: navigation failed`); continue; }
    if (v.overflowX > 1) errors.push(`${label}: horizontal overflow ${v.overflowX}px`);
    if (v.blank < 200) errors.push(`${label}: page looks blank (${v.blank} chars)`);
    for (const e of consoleEvents) {
      const txt = JSON.stringify(e.params || e).slice(0, 300);
      // ignore known-harmless software-WebGL deprecation noise from headless Chromium
      if (/GroupMarkerNotSet|WebGL.*software|SwiftShader/i.test(txt)) continue;
      if (e.method === 'Runtime.consoleAPICalled' && ['error'].includes(e.params.type)) errors.push(`${label}: console.error ${txt}`);
      else if (e.method === 'Runtime.exceptionThrown') errors.push(`${label}: exception ${txt}`);
      else if (e.method === 'Log.entryAdded' && ['error'].includes(e.params.entry.level)) errors.push(`${label}: log.error ${txt}`);
    }
  }
}
ws.close();
// Wait for Chrome to exit before deleting its profile: deleting while it still
// writes raced (ENOTEMPTY) and crashed the gate after a clean render.
await new Promise((r) => { chrome.once('exit', r); chrome.kill(); setTimeout(r, 5000); });
try { fs.rmSync(prof, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 }); } catch {}
if (errors.length) { console.log('RENDER_BAD'); errors.slice(0, 12).forEach(e => console.log('  ' + e)); process.exit(1); }
console.log(`RENDER_OK ${PAGES.length}x${VIEWPORTS.length} page-views, zero console errors, zero overflow`);
MEOF
if node "$I_TMP/render.mjs" > "$I_TMP/render.out" 2> "$I_TMP/render.err"; then
  pass "I headless render ($(cat "$I_TMP/render.out" | head -1 | sed 's/RENDER_OK //'))"
else
  fail "I headless render" "$(head -6 "$I_TMP/render.out" "$I_TMP/render.err" | tr '\n' ';' | head -c 600)"
fi
rm -rf "$I_TMP"

# ============ Gate J: no deleted-path references ============
echo "== J  deleted paths =="
J_BAD="$(cd "$SITE_DIR" && grep -rln --include='*.html' --include='*.js' -E 'reader-template|/old/|/drafts/|lorem ipsum|\.bak|TODO\.html' . | grep -v '^\./scripts/' || true)"
if [ -z "$J_BAD" ]; then
  pass "J no deleted-path references"
else
  fail "J no deleted-path references" "$(echo "$J_BAD" | tr '\n' ' ')"
fi

# ============ Gate K: agent stack evidence ============
# K1 verdict files complete and independently reviewed, K2 quoted citations resolve,
# K3 rigor-practices.tsv sources and proofs, K4 generated pages equal a fresh run.
# Rules: ../../stack/METHOD.md. Details: ../BUILD-GATES.md.
echo "== K  agent stack evidence =="
K_OUT="$(python3 - <<'PYEOF'
import re, os, subprocess
root = os.environ['REPO_ROOT']
TIERS = ['Verified', 'CI-observed', 'Maintainer claim', 'External', 'Inference']
GROUPS = ['Model serving', 'Orchestration', 'Tools and environment', 'Memory and retrieval',
          'Eval and safety', 'Training and voice']
VERDICTS = ['Adopt', 'Adopt and wrap', 'Build clean-room', 'Watch']
CONF = ['High', 'Medium', 'Low']
KEYS = ['type', 'title', 'group', 'verdict', 'confidence', 'evidence_date', 'author', 'reviewed_by', 'review_date']
SECTIONS = ['Bottom line', 'Adopt, do not rebuild', 'Copy these practices', 'Build only if',
            'Where FrankenSuite touches this', 'What we cannot say', 'Revisit when']
FACTUAL = SECTIONS[1:5]
QUOTED = FACTUAL + ['What we cannot say']
# <path with extension>:<line>[-<line>] "<quote>"; same shape make-stack.mjs renders.
CITE = re.compile(r'(?<![\w/.:#-])((?:[\w.-]+/)*[\w-][\w.-]*\.[A-Za-z][A-Za-z0-9]*):(\d+)(?:[-\u2013](\d+))?(?!\w)(?:\s+"([^"\n]*)")?')
# References inside an our_proof token: "commit <sha>" / a sha, or a repo path (has a "/" or a known
# extension) with an optional :line. URLs are skipped by the look-behind. make-stack.mjs links the same shapes.
PROOF_REF = re.compile(r'(commit\s+)?\b([0-9a-f]{7,40})\b|(?<![\w/:.-])((?:\.?[\w-][\w.-]*/)+[\w.-]*[\w-]|[\w-][\w.-]*\.(?:md|sh|yml|yaml|tsv|json|mjs|js|py|html|toml|txt))(?::(\d+))?')
TIER_OK = re.compile(r'\[(?:' + '|'.join(re.escape(t) for t in TIERS) + r')(?:[,;][^\]\n]*)?\]')
TIERISH = re.compile(r'(?i)^T\d|verified|observed|claim|external|inference|counted|absence')
DATE = re.compile(r'^\d{4}-\d{2}-\d{2}$')
out = {'K1': [], 'K2': [], 'K3': []}
stats = {'files': 0, 'cites': 0, 'rows': 0}

def norm(s):
    return re.sub(r'\s+', ' ', re.sub(r'[*`]', '', s)).strip()

_cache = {}
def lines_of(p):
    if p.startswith('/') or '..' in p.split('/'):
        return None
    full = os.path.join(root, p)
    if not os.path.isfile(full):
        return None
    if p not in _cache:
        _cache[p] = open(full, encoding='utf-8', errors='replace').read().split('\n')
    return _cache[p]

def check_cite(p, a, b, quote, need_quote):
    """Errors for one citation: file, line(s), non-empty, and the quote on those lines."""
    ls = lines_of(p)
    ref = '%s:%s%s' % (p, a, '-%s' % b if b != a else '')
    if ls is None:
        return ['%s: file not in repo' % ref]
    if a < 1 or b < a or b > len(ls):
        return ['%s: line out of range (file has %d lines)' % (ref, len(ls))]
    if not ls[a - 1].strip() or not ls[b - 1].strip():
        return ['%s: cited line is empty' % ref]
    if quote is None:
        return ['%s: citation has no quote' % ref] if need_quote else []
    q = norm(quote)
    if len(q) < 20:
        return ['%s: quote shorter than 20 characters: "%s"' % (ref, q)]
    if q not in norm(' '.join(ls[a - 1:b])):
        return ['%s: quote not on the cited line: "%s"' % (ref, q[:70])]
    return []

slugs = sorted(f[7:-3] for f in os.listdir(os.path.join(root, 'ecosystem/pickup'))
               if f.startswith('pickup-') and f.endswith('.md'))
if not slugs:
    out['K1'].append('empty scan set: no ecosystem/pickup/pickup-*.md types found')
present = sorted(f[:-3] for f in os.listdir(os.path.join(root, 'stack')) if f.endswith('.md') and f != 'METHOD.md')
for extra in sorted(set(present) - set(slugs)):
    out['K1'].append('stack/%s.md: no matching ecosystem/pickup/pickup-%s.md type' % (extra, extra))

for slug in slugs:
    rel = 'stack/%s.md' % slug
    k1, k2 = [], []
    if not os.path.isfile(os.path.join(root, rel)):
        out['K1'].append('%s: missing' % rel)
        continue
    stats['files'] += 1
    src = open(os.path.join(root, rel), encoding='utf-8').read()
    fm, body = {}, src
    m = re.match(r'---\n(.*?)\n---\n?', src, re.S)
    if not m:
        k1.append('no front matter')
    else:
        for l in m.group(1).split('\n'):
            km = re.match(r'([A-Za-z_]+):\s*(.*)$', l)
            if km:
                fm[km.group(1)] = km.group(2).strip()
        body = src[m.end():]
    for k in KEYS:
        if not fm.get(k):
            k1.append('%s missing' % k)
    if fm.get('type') and fm['type'] != slug:
        k1.append('type %r != file slug' % fm['type'])
    if fm.get('group') and fm['group'] not in GROUPS:
        k1.append('group %r not one of the six' % fm['group'])
    if fm.get('verdict') and fm['verdict'] not in VERDICTS:
        k1.append('verdict %r not in the four-value set' % fm['verdict'])
    if fm.get('confidence') and fm['confidence'] not in CONF:
        k1.append('confidence %r not High/Medium/Low' % fm['confidence'])
    for k in ('evidence_date', 'review_date'):
        if fm.get(k) and not DATE.match(fm[k]):
            k1.append('%s %r is not YYYY-MM-DD' % (k, fm[k]))
    if fm.get('reviewed_by') and fm['reviewed_by'] == fm.get('author'):
        k1.append('reviewed_by equals author (%s)' % fm['author'])
    secs, cur = {}, None
    for l in body.split('\n'):
        hm = re.match(r'## (.+?)\s*$', l)
        if hm:
            cur = hm.group(1)
            secs[cur] = []
        elif cur is not None:
            secs[cur].append(l)
    for s in SECTIONS:
        if s not in secs:
            k1.append('section "## %s" missing' % s)
    if 'What we cannot say' in secs and not '\n'.join(secs['What we cannot say']).strip():
        k1.append('"What we cannot say" is empty')
    bl = '\n'.join(secs.get('Bottom line', [])).strip()
    if 'Bottom line' in secs and not re.sub(r'^[*_\s]+', '', bl).startswith('Inference'):
        k1.append('Bottom line does not start with "Inference"')
    rej = fm.get('rejected_alternative', '')
    if fm.get('verdict') == 'Build clean-room':
        if not rej:
            k1.append('Build clean-room without rejected_alternative')
        elif not CITE.search(rej):
            k1.append('rejected_alternative has no citation')
    # K2: every citation in the file, front matter included.
    cited = []
    def scan(text, need_quote):
        for c in CITE.finditer(text):
            a = int(c.group(2)); b = int(c.group(3) or a)
            cited.append((c.group(1), a, b))
            stats['cites'] += 1
            k2.extend(check_cite(c.group(1), a, b, c.group(4), need_quote))
    scan(rej, True)
    for s, ls in secs.items():
        scan('\n'.join(ls), s in QUOTED)
    # Tier tokens: only the Rulebook's five (quotes and code spans are not scanned).
    stripped = CITE.sub(lambda c: c.group(1), body)
    stripped = re.sub(r'`[^`\n]*`', '', stripped)
    for t in re.finditer(r'\[([^\]\n]+)\](?!\()', stripped):
        head = re.split(r'[,;]', t.group(1))[0].strip()
        if head not in TIERS and TIERISH.search(head):
            k2.append('non-Rulebook tier token [%s]' % t.group(1))
    # Every factual bullet: at least one citation and a Rulebook tier.
    for s in FACTUAL:
        items = []
        for l in secs.get(s, []):
            if re.match(r'\s{0,1}[-*]\s+', l):
                items.append(l)
            elif items and re.match(r'\s+\S', l):
                items[-1] += ' ' + l.strip()
        for it in items:
            if not CITE.search(it):
                k2.append('%s bullet without citation: %s' % (s, it.strip()[:60]))
            if not TIER_OK.search(it):
                k2.append('%s bullet without a Rulebook tier: %s' % (s, it.strip()[:60]))
    # At least one citation into the evidence pack's caveats section, when it has one.
    pack = 'ecosystem/pickup/_evidence/%s.md' % slug
    pl = lines_of(pack)
    if pl:
        hs = [i for i, l in enumerate(pl) if re.match(r'##\s+.*(caveat|note)', l, re.I) and not l.startswith('###')]
        if hs:
            lo = hs[0] + 1
            hi = next((i for i in range(lo, len(pl)) if pl[i].startswith('## ')), len(pl))
            if not any(p == pack and a <= hi and b >= lo for p, a, b in cited):
                k2.append('no citation into %s caveats section (lines %d-%d)' % (pack, lo, hi))
    if k1:
        out['K1'].append('%s: %s' % (rel, '; '.join(k1)))
    for e in k2:
        out['K2'].append('%s: %s' % (rel, e))
if stats['files'] and not stats['cites']:
    out['K2'].append('empty scan set: zero citations in stack/*.md')
if not stats['files']:
    out['K2'].append('empty scan set: no verdict files to check')

# K3: stack/rigor-practices.tsv
TSV = 'stack/rigor-practices.tsv'
HEADER = 'id\tpractice\twhat_to_copy\tareas\tevidenced_in\tsource\tsource_quote\tchecklist\tour_status\tour_proof'
if not os.path.isfile(os.path.join(root, TSV)):
    out['K3'].append('%s missing' % TSV)
else:
    tl = [l for l in open(os.path.join(root, TSV), encoding='utf-8').read().split('\n') if l.strip()]
    if not tl or tl[0] != HEADER:
        out['K3'].append('header is not exactly: %s' % HEADER.replace('\t', ' | '))
    kit = set(re.findall(r'^### ([A-Z]\d+) ', open(os.path.join(root, 'starter-kit/CHECKLIST.md')).read(), re.M))
    areas_ok = set(slugs) | {'frankensuite'}
    for i, l in enumerate(tl[1:], 1):
        c = l.split('\t')
        stats['rows'] += 1
        rid = c[0] if c else '?'
        if len(c) != 10:
            out['K3'].append('row %d: %d columns, want 10' % (i, len(c))); continue
        r = dict(zip(HEADER.split('\t'), [x.strip() for x in c]))
        if r['id'] != 'RP-%03d' % i:
            out['K3'].append('row %d: id %r, want RP-%03d' % (i, r['id'], i))
        sm = re.match(r'^([\w./-]+):(\d+)$', r['source'])
        if not sm:
            out['K3'].append('%s: source %r is not path:line' % (rid, r['source']))
        else:
            for e in check_cite(sm.group(1), int(sm.group(2)), int(sm.group(2)), r['source_quote'], True):
                out['K3'].append('%s: %s' % (rid, e))
        bad_areas = [a for a in r['areas'].split(';') if a.strip() not in areas_ok]
        if bad_areas or not r['areas']:
            out['K3'].append('%s: areas not in the 21 slugs or frankensuite: %r' % (rid, bad_areas or r['areas']))
        ck = [x.strip() for x in r['checklist'].split(';') if x.strip()]
        if ck != ['none'] and (not ck or any(x not in kit for x in ck)):
            out['K3'].append('%s: checklist %r has ids not headed "### <id> " in starter-kit/CHECKLIST.md' % (rid, r['checklist']))
        if r['our_status'] not in ('adopted', 'partial', 'candidate', 'not-applicable'):
            out['K3'].append('%s: our_status %r not adopted|partial|candidate|not-applicable' % (rid, r['our_status']))
        if r['our_status'] in ('adopted', 'partial'):
            # our_proof is ';'-separated. A token may carry a label ("done: ...", "missing: ...");
            # missing/todo/gap tokens name what is absent and are not proofs. In every other token,
            # each path reference (with a "/" or a known file extension, optional :line) must exist,
            # and each "commit <sha>" (or a token that is only a sha) must pass git cat-file -e.
            ok, bad = 0, []
            for tok in [t.strip() for t in r['our_proof'].split(';') if t.strip()]:
                lm = re.match(r'^([A-Za-z][A-Za-z ]*):\s+(.*)$', tok)
                if lm:
                    if lm.group(1).strip().lower() in ('missing', 'todo', 'gap', 'not yet'):
                        continue
                    tok = lm.group(2).strip()
                for pm in PROOF_REF.finditer(tok):
                    sha, ref, line = pm.group(2), pm.group(3), pm.group(4)
                    if sha:
                        if not pm.group(1) and tok != sha:
                            continue  # a bare hex word inside prose is not a commit reference
                        rc = subprocess.run(['git', '-C', root, 'cat-file', '-e', sha + '^{commit}'],
                                            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode
                        (bad.append(pm.group(0)) if rc else None); ok += (rc == 0)
                    else:
                        ls = lines_of(ref)
                        good = ls is not None and (not line or 1 <= int(line) <= len(ls))
                        if ls is None and os.path.isdir(os.path.join(root, ref)) and not line:
                            good = True
                        (None if good else bad.append(pm.group(0))); ok += good
            if bad or not ok:
                out['K3'].append('%s: %s but proof does not resolve: %r' % (rid, r['our_status'], bad or r['our_proof']))
    if not stats['rows']:
        out['K3'].append('empty scan set: %s has no rows' % TSV)

# K5: every owner/repo in **bold** in an "Adopt, do not rebuild" bullet has a stack/licenses.tsv row,
# and a non-permissive license is named in that bullet's own words (METHOD rule 9).
out['K5'] = []
LTSV = 'stack/licenses.tsv'
LHEAD = 'repo\tspdx\tlicense_class\tchecked\tcommand\tnote'
LCLASSES = ['permissive', 'weak-copyleft', 'strong-copyleft', 'network-copyleft', 'source-available',
            'permissive-with-conditions', 'none', 'unknown']
REPO = re.compile(r'(?<![\w./-])([A-Za-z0-9][\w.-]*/[A-Za-z0-9](?:[\w.-]*[A-Za-z0-9_])?)')
NO_SPDX = {'', '-', 'NOASSERTION', 'NONE', 'OTHER', 'UNKNOWN'}
ALIASES = {'BUSL': ['BSL', 'Business Source'], 'SSPL': ['Server Side Public License'], 'AGPL': ['Affero'],
           'Elastic': ['Elastic License'], 'LGPL': ['Lesser General Public'], 'MPL': ['Mozilla Public']}
NOTE_NAMES = ['SSPL', 'Server-Side Public License', 'BSL', 'BUSL', 'Elastic', 'ELv2', 'AGPL', 'Affero', 'LGPL', 'GPL',
              'MPL', 'EPL', 'Commons Clause', 'OpenRAIL', 'RAIL', 'CC-BY-NC', 'non-commercial', 'noncommercial',
              'Community License', 'Enterprise License', 'Enterprise Edition', 'commercial license', 'proprietary',
              'LTX-2']
# Permissive SPDX ids never "name" a non-permissive license: "MIT" in a bullet says nothing about an AGPL part.
PERMISSIVE_IDS = {'MIT', 'MIT-0', 'Apache-2.0', 'Apache-1.1', 'BSD-2-Clause', 'BSD-3-Clause', 'ISC', '0BSD',
                  'Unlicense', 'Zlib', 'BSL-1.0', 'CC0-1.0', 'PSF-2.0', 'Python-2.0', 'X11', 'UPL-1.0'}
CLASS_WORDS = {
    'source-available': ['source-available', 'source available'],
    'permissive-with-conditions': ['condition', 'conditions'],
    'none': ['no license', 'no licence', 'unlicensed', 'without a license', 'no open-source license', 'no LICENSE file'],
    'unknown': ['license unknown', 'unknown license', 'license is unknown', 'license unclear', 'unclear license',
                'license could not be determined', 'license not determined'],
}
lic = {}
stats['lic'] = 0; stats['adopted'] = 0
if not os.path.isfile(os.path.join(root, LTSV)):
    out['K5'].append('%s missing' % LTSV)
else:
    ll = [l for l in open(os.path.join(root, LTSV), encoding='utf-8').read().split('\n') if l.strip()]
    if not ll or ll[0] != LHEAD:
        out['K5'].append('%s header is not exactly: %s' % (LTSV, LHEAD.replace('\t', ' | ')))
    for i, l in enumerate(ll[1:], 2):
        c = [x.strip() for x in l.split('\t')]
        if len(c) != 6:
            out['K5'].append('%s line %d: %d columns, want 6' % (LTSV, i, len(c))); continue
        r = dict(zip(LHEAD.split('\t'), c))
        stats['lic'] += 1
        if not re.fullmatch(REPO.pattern, r['repo']):
            out['K5'].append('%s line %d: repo %r is not owner/repo' % (LTSV, i, r['repo']))
        if r['license_class'] not in LCLASSES:
            out['K5'].append('%s line %d: license_class %r not in the eight classes' % (LTSV, i, r['license_class']))
        if not DATE.match(r['checked']):
            out['K5'].append('%s line %d: checked %r is not YYYY-MM-DD' % (LTSV, i, r['checked']))
        if r['repo'].lower() in lic:
            out['K5'].append('%s line %d: duplicate row for %s' % (LTSV, i, r['repo']))
        lic[r['repo'].lower()] = r
    if not stats['lic']:
        out['K5'].append('empty scan set: %s has no rows' % LTSV)

def license_names(r):
    """(label, regex) pairs; any one found in the bullet's prose names this row's license."""
    names = []
    word = lambda s: (s, r'(?<![\w])%s(?![\w])' % re.escape(s))
    for comp in re.split(r'\s+(?:AND|OR|WITH)\s+|[()]', r['spdx']):
        comp = comp.strip()
        if not comp or comp.upper() in NO_SPDX or comp in PERMISSIVE_IDS:
            continue
        if comp.startswith('LicenseRef-'):
            # LicenseRef-Llama-3.2-Community -> "Llama ... license" within a few words.
            first = comp[len('LicenseRef-'):].split('-')[0]
            if len(first) >= 3:
                names.append(('%s ... license' % first, r'(?<![\w])%s[\w\s.,/-]{0,40}?licen[cs]e' % re.escape(first)))
            continue
        names.append(word(comp))
        fam = re.match(r'[A-Za-z]+', comp)
        if fam and len(fam.group(0)) >= 3:
            names.append(word(fam.group(0)))
            names.extend(word(a) for a in ALIASES.get(fam.group(0), []))
    names.extend(word(w) for w in CLASS_WORDS.get(r['license_class'], []))
    names.extend(word(n) for n in NOTE_NAMES if re.search(r'(?<![\w-])%s(?![\w])' % re.escape(n), r['note'], re.I))
    return list(dict.fromkeys(names))

for slug in slugs:
    rel = 'stack/%s.md' % slug
    if not os.path.isfile(os.path.join(root, rel)):
        continue
    body = open(os.path.join(root, rel), encoding='utf-8').read()
    sm = re.search(r'^## Adopt, do not rebuild\s*\n(.*?)(?=^## |\Z)', body, re.S | re.M)
    items = []
    for l in (sm.group(1).split('\n') if sm else []):
        if re.match(r'\s{0,1}[-*]\s+', l):
            items.append(l)
        elif items and re.match(r'\s+\S', l):
            items[-1] += ' ' + l.strip()
    for it in items:
        # The author's words: quoted evidence and the adopted repo names themselves do not count.
        prose = CITE.sub(lambda c: c.group(1), it)
        prose = re.sub(r'\*\*(.+?)\*\*', lambda m: REPO.sub('', m.group(1)), prose)
        for b in re.findall(r'\*\*(.+?)\*\*', it):
            for repo in REPO.findall(b):
                stats['adopted'] += 1
                r = lic.get(repo.lower())
                if r is None:
                    out['K5'].append('%s: adopted %s has no %s row' % (rel, repo, LTSV))
                    continue
                if r['license_class'] == 'permissive':
                    continue
                names = license_names(r)
                if not any(re.search(rx, prose, re.I) for _, rx in names):
                    out['K5'].append('%s: adopted %s is %s (%s) but its bullet does not name the license (looked for: %s)'
                                     % (rel, repo, r['license_class'], r['spdx'] or 'no spdx',
                                        ', '.join(n for n, _ in names) or 'nothing to match'))
if stats['files'] and not stats['adopted']:
    out['K5'].append('empty scan set: no owner/repo in bold under "Adopt, do not rebuild" in any verdict')

print('KSTATS files=%d/%d cites=%d rows=%d licenses=%d adopted=%d' % (
    stats['files'], len(slugs), stats['cites'], stats['rows'], stats['lic'], stats['adopted']))
for k in ('K1', 'K2', 'K3', 'K5'):
    for e in out[k]:
        print('%s %s' % (k, e))
print('K_DONE')
PYEOF
)"
K_STATS="$(printf '%s\n' "$K_OUT" | sed -n 's/^KSTATS //p')"
k_report() {  # $1 = sub-gate id, $2 = label; PASS only if the checker finished and printed no findings
  local lines n
  lines="$(printf '%s\n' "$K_OUT" | grep "^$1 " || true)"
  if ! printf '%s\n' "$K_OUT" | grep -q '^K_DONE'; then
    fail "$1 $2" "checker crashed: $(printf '%s\n' "$K_OUT" | tail -3 | tr '\n' ';')"
  elif [ -z "$lines" ]; then
    pass "$1 $2 ($K_STATS)"
  else
    n="$(printf '%s\n' "$lines" | wc -l | tr -d ' ')"
    fail "$1 $2" "$n finding(s):"
    printf '%s\n' "$lines" | head -40 | sed 's/^/        /'
    [ "$n" -gt 40 ] && echo "        ... and $((n - 40)) more"
  fi
}
k_report K1 "verdict files complete and independently reviewed"
k_report K2 "quoted citations resolve"
k_report K3 "rigor practices sources and proofs"

# K4: the shipped pages are exactly what make-stack.mjs produces from today's sources.
K4_TMP="$(mktemp -d)"
K4_RUN="$(node "$SITE_DIR/scripts/make-stack.mjs" --out "$K4_TMP" 2>&1)"; K4_RC=$?
K4_DIFF=""
K4_N="$(ls "$K4_TMP"/stack/*.html "$K4_TMP"/rigor/*.html 2>/dev/null | wc -l | tr -d ' ')"
for d in stack rigor; do
  if [ -d "$K4_TMP/$d" ] || [ -d "$SITE_DIR/$d" ]; then
    K4_DIFF="$K4_DIFF$(diff -rq "$SITE_DIR/$d" "$K4_TMP/$d" 2>&1 | sed -e "s#$K4_TMP#<fresh>#g" -e "s#$SITE_DIR#site#g")"
  fi
done
rm -rf "$K4_TMP"
if [ $K4_RC -ne 0 ]; then
  fail "K4 generated pages match their sources" "make-stack.mjs exited $K4_RC: $K4_RUN"
elif [ "${K4_N:-0}" -eq 0 ]; then
  fail "K4 generated pages match their sources" "empty scan set: a fresh run produced no pages"
elif [ -n "$K4_DIFF" ]; then
  fail "K4 generated pages match their sources" "rerun node site/scripts/make-stack.mjs: $(echo "$K4_DIFF" | head -4 | tr '\n' ';')"
else
  pass "K4 generated pages match their sources ($K4_N pages byte-identical to a fresh run)"
fi
k_report K5 "adopted incumbents have a checked license, named when not permissive"

# ============ Gate L: no personal email addresses ============
# Every git-tracked text file in the repo. Allowed: noreply@*, *@users.noreply.github.com, and the
# starter kit's documented placeholder you@example.com (starter-kit/README.md, starter-kit/scripts/init.sh).
echo "== L  no personal email addresses =="
L_OUT="$(python3 - <<'PYEOF'
import re, os, subprocess
root = os.environ['REPO_ROOT']
EMAIL = re.compile(r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}')
def allowed(e):
    e = e.lower()
    return e.startswith('noreply@') or e.endswith('@users.noreply.github.com') or e == 'you@example.com'
p = subprocess.run(['git', '-C', root, 'ls-files', '-z'], capture_output=True)
files = [f for f in p.stdout.decode('utf-8', 'replace').split('\0') if f] if p.returncode == 0 else []
hits, scanned = [], 0
for f in files:
    full = os.path.join(root, f)
    if not os.path.isfile(full):
        continue
    b = open(full, 'rb').read()
    if b'\0' in b[:8192]:
        continue  # binary
    scanned += 1
    for i, line in enumerate(b.decode('utf-8', 'replace').split('\n'), 1):
        for e in EMAIL.findall(line):
            if not allowed(e):
                hits.append('%s:%d %s' % (f, i, e))
print('SCANNED %d' % scanned)
if p.returncode != 0:
    print('  git ls-files failed: %s' % p.stderr.decode('utf-8', 'replace').strip()[:200])
elif scanned == 0:
    print('  empty scan set: no tracked text files')
for h in hits:
    print('  ' + h)
PYEOF
)"
L_N="$(count_of "$L_OUT" SCANNED)"
L_BAD="$(printf '%s\n' "$L_OUT" | grep '^  ' || true)"
if [ "${L_N:-0}" -gt 0 ] && [ -z "$L_BAD" ]; then
  pass "L no personal email addresses ($L_N tracked text files)"
else
  fail "L no personal email addresses" "$(printf '%s\n' "$L_BAD" | wc -l | tr -d ' ') finding(s):"
  printf '%s\n' "$L_BAD" | head -40 | sed 's/^/      /'
fi

# ============ summary ============
echo "----------------------------------------"
echo "gates passed: $PASS   failed: $FAIL"
if [ $FAIL -gt 0 ]; then
  echo "failed gates: ${FAILED_GATES[*]}"
  exit 1
fi
echo "ALL GATES PASS"
